### ISSUE TITLE
vim-go not detected when using vim-plug

### ISSUE THREAD

**Issue by heliostatic** [rakyll/govalidate#2]
~It looks like `vim-go` is not detected if installed via https://github.com/junegunn/vim-plug~

The path checked here: https://github.com/rakyll/govalidate/blob/95ca3ee38065f48f35977d7268e56a35b7a8985d/check/checkvim.go#L25 seems like it doesn't include the `plugged` directory.

Edit: Completely unrelated to the plugin manager, actually about symlinks. Thanks for creating this tool (and your work on Go)!

**Comment by heliostatic** [comment]
Ah, reading the documentation helps... my `.vim` directory is actually a symlink, which I guess filepath.Walk doesn't follow per https://golang.org/pkg/path/filepath/#Walk

Still a bug for me, but not sure how you'd like to handle.

**Comment by rakyll** [comment]
We should handle symlinks, I will send a fix later today.
